(test) allow repeated tests for prox, POGS

diff --git a/test b/test
--- a/test
+++ b/test
@@ -152,8 +152,23 @@ for transpose in ${TRANSPOSE_STATES[@]}; do
 			make libprox FLOAT=$FLOAT GPU=$GPU
 		fi
 		echo TESTING PROX CALLS
-		nosetests ${testprefix}prox${suffix}
-		TEST_FAILURE=$(($? || $TEST_FAILURE))
+
+		repeated_test_status=1
+		# give test 5 chances to pass
+		# loosen numerical tolerance on subsequent tries
+		for test_counter in `seq 0 4`
+		do
+			export OPTKIT_REPEAT_NUMERICALTEST=${test_counter}
+			nosetests ${testprefix}prox${suffix}
+			proj_status=$(( $? && repeated_test_status ))
+			if (( repeated_test_status == 0  )); then
+				break;
+			else
+				echo "PROX test failed (attempt of" $((test_counter + 1)) "of 5)";
+			fi			
+		done
+		TEST_FAILURE=$(($repeated_test_status || $TEST_FAILURE))
+		export OPTKIT_REPEAT_NUMERICALTEST=0
 	fi
 
 	if [[ ${OPERATOR:-0} -eq 1 ]]; then
@@ -185,21 +200,22 @@ for transpose in ${TRANSPOSE_STATES[@]}; do
 		fi
 		echo TESTING CG CALLS: ${msg}
 
-		cg_status=1
+		repeated_test_status=1
 		# CG test success numerically sensitive. give it 5 chances to pass
 		# loosen numerical tolerance on subsequent tries
-		for cg_counter in `seq 0 4`
+		for test_counter in `seq 0 4`
 		do
-			export OPTKIT_REPEAT_CGTEST=${cg_counter}
+			export OPTKIT_REPEAT_NUMERICALTEST=${test_counter}
 			nosetests ${testprefix}cg${suffix}
-			cg_status=$(( $? && cg_status ))
-			if (( cg_status == 0  )); then
+			repeated_test_status=$(( $? && repeated_test_status ))
+			if (( repeated_test_status == 0  )); then
 				break;
 			else
-				echo "CG test failed (attempt of" $((cg_counter + 1)) "of 5)";
+				echo "CG test failed (attempt of" $((test_counter + 1)) "of 5)";
 			fi
 		done 
 		TEST_FAILURE=$(($cg_status || $TEST_FAILURE))
+		export OPTKIT_REPEAT_NUMERICALTEST=0
 	fi
 
 	if [[ ${EQUIL:-0} -eq 1 ]]; then	
@@ -219,22 +235,22 @@ for transpose in ${TRANSPOSE_STATES[@]}; do
 		fi
 		echo TESTING PROJECTOR CALLS: ${msg}
 
-		proj_status=1
-		# CG test success numerically sensitive. give it 5 chances to pass
+		repeated_test_status=1
+		# give test 5 chances to pass
 		# loosen numerical tolerance on subsequent tries
-		for proj_counter in `seq 0 4`
+		for test_counter in `seq 0 4`
 		do
-			export OPTKIT_REPEAT_PROJTEST=${proj_counter}
+			export OPTKIT_REPEAT_NUMERICALTEST=${test_counter}
 			nosetests ${testprefix}projector${suffix}
-			proj_status=$(( $? && proj_status ))
-			if (( proj_status == 0  )); then
+			proj_status=$(( $? && repeated_test_status ))
+			if (( repeated_test_status == 0  )); then
 				break;
 			else
-				echo "PROJECTION test failed (attempt of" $((proj_counter + 1)) "of 5)";
+				echo "PROJECTION test failed (attempt of" $((test_counter + 1)) "of 5)";
 			fi			
 		done
-
-		TEST_FAILURE=$(($proj_status || $TEST_FAILURE))
+		TEST_FAILURE=$(($repeated_test_status || $TEST_FAILURE))
+		export OPTKIT_REPEAT_NUMERICALTEST=0
 	fi
 				
 	if [[ ${POGS_DENSE:-0} -eq 1 ]]; then
@@ -245,8 +261,23 @@ for transpose in ${TRANSPOSE_STATES[@]}; do
 		fi
 		export OPTKIT_DEBUG_PYTHON=0
 		echo TESTING \(DENSE\) POGS CALLS: ${msg}
-		nosetests ${testprefix}pogs${suffix}
-		TEST_FAILURE=$(($? || $TEST_FAILURE))
+
+		repeated_test_status=1
+		# give test 5 chances to pass
+		# loosen numerical tolerance on subsequent tries
+		for test_counter in `seq 0 4`
+		do
+			export OPTKIT_REPEAT_NUMERICALTEST=${test_counter}
+			nosetests ${testprefix}pogs${suffix}
+			proj_status=$(( $? && repeated_test_status ))
+			if (( repeated_test_status == 0  )); then
+				break;
+			else
+				echo "POGS test failed (attempt of" $((test_counter + 1)) "of 5)";
+			fi			
+		done
+		TEST_FAILURE=$(($repeated_test_status || $TEST_FAILURE))
+		export OPTKIT_REPEAT_NUMERICALTEST=0
 	fi
 
 	if [[ ${POGS_ABSTRACT:-0} -eq 1 ]]; then
